#spring:
#  activemq:
#    broker-url: tcp://localhost:61616
#



mybatis:
  mapper-locations: classpath:/com/learn/mqtx/**/*.xml
  configuration:
    auto-mapping-unknown-column-behavior: warning
    map-underscore-to-camel-case: true
spring:
  datasource:
    url: jdbc:mysql://192.168.163.184:3306/test?characterEncoding=utf8&useUnicode=true
    username: live
    password: admin
